In [5]:
import numpy as np

In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [10]:
a.sum(0)

array([5, 7, 9])

In [13]:
count=0
nextnode=[1,2,3,4,5]
index_reg=[1,2,3,8,9,6]
next=np.setdiff1d(nextnode,index_reg)
count+=(len(nextnode)-len(next))

In [14]:
nextnode

[1, 2, 3, 4, 5]

In [15]:
next

array([4, 5])

In [16]:
count

3

In [21]:
a=np.array([1,2,3])
b=np.array([1,2,3,4])

In [22]:
c=np.hstack((a,b))

In [23]:
c

array([1, 2, 3, 1, 2, 3, 4])

In [27]:
np.hstack((a,np.where(c==1)[0]))

array([1, 2, 3, 0, 3], dtype=int64)